### ISSUE TITLE
[ToDo] Remake image using new tag

### ISSUE THREAD

**Issue by MiguelNdeCarvalho** [MiguelNdeCarvalho/docker-miguelndecarvalho-repo#3]
- [x] Use `base-devel` tag
- [x] Remove `base-devel` from install
- [x] Make more steps
- [x] Delete stuff to decrease image space
